### ISSUE TITLE
Remove Wooey's Re-run and Resubmit buttons from the Raintale GUI

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/raintale#25]
They are confusing to us and will likely be so for users. Until we can articulate how to use them, we should remove them.

We just need someone to remove the lines from `raintale-gui/templates/jobs/job_view.html`:

https://github.com/oduwsdl/raintale/blob/a2e219a824c97eff943ab283457ab220b081cd93/raintale-gui/templates/jobs/job_view.html#L114-L119

**Comment by himarshaj** [comment]
Reviewed it at Monday's meeting. Closing.
