### ISSUE TITLE
Remove Raintale GUI's Download button

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/raintale#27]
Wooey has a confusing setup with respect to Downloads.  We will be implementing a "View Story" button in #26 which will make the existing `Download` button redundant. We should remove the `Download` button so that it does not confuse users.

The code to do so is here:
https://github.com/oduwsdl/raintale/blob/a2e219a824c97eff943ab283457ab220b081cd93/raintale-gui/templates/jobs/job_view.html#L40-L53

**Comment by himarshaj** [comment]
In a review during Monday's meeting, we decide to go in a different direction. Opened #34.

Closing.
