### ISSUE TITLE
For Raintale GUI, remove user option to specify output filename

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/raintale#31]
Per feedback from @ato, if we allow users to specify an output file, they could abuse the server and overwrite existing system files. We really do not need to provide this option. To avoid this security issue, we should do two things for all Raintale scripts that have output files:

1. remove the option of specifying an output filename from all GUI scripts - this addresses the security concern
2. make the default output filename `output.dat` or `story-file.dat` with an appropriate extension - I'm leaning toward `story-file.dat` or `story.dat` or something like that -- just make sure it is descriptive and matches the work done in #26 

This should not affect stories that use social media because there is no output filename.

**Comment by himarshaj** [comment]
Reviewed it during Monday's meeting.

Closing.
