### ISSUE TITLE
set-raintale-database.sh: references non-existent hypercane_with_wooey directory

### ISSUE THREAD

**Issue by ato** [oduwsdl/raintale#43]
```
writing database information to /opt/raintale/raintale-gui/../hypercane_with_wooey/hypercane_with_wooey/settings/user_settings.py
/opt/raintale/raintale-gui/set-raintale-database.sh: line 118: /opt/raintale/raintale-gui/../hypercane_with_wooey/hypercane_with_wooey/settings/user_settings.py: No such file or directory
```

I assume that should be raintale_with_wooey not hypercane_with_wooey. There are some other references to hypercane in the script that probably don't belong:

https://github.com/oduwsdl/raintale/blob/c8885ffa63ef9e3d869522d98749ed18179d16e2/raintale-gui/set-raintale-database.sh#L17
https://github.com/oduwsdl/raintale/blob/c8885ffa63ef9e3d869522d98749ed18179d16e2/raintale-gui/set-raintale-database.sh#L31
https://github.com/oduwsdl/raintale/blob/c8885ffa63ef9e3d869522d98749ed18179d16e2/raintale-gui/set-raintale-database.sh#L102
https://github.com/oduwsdl/raintale/blob/c8885ffa63ef9e3d869522d98749ed18179d16e2/raintale-gui/set-raintale-database.sh#L150

**Comment by shawnmjones** [comment]
As noted in #42, this was due to a bad copy/paste. Thanks.

**Comment by ato** [comment]
I tested the new version and this problem was resolved.
