### ISSUE TITLE
Examine if Wooey can create textareas for pasting lists of URI-Ms

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/raintale#48]
As suggested by @ato, it would be cool if the user could, instead of submitting a file containing a list of URI-Ms, they could instead paste a list of URI-Ms into a textarea as input.

**Comment by himarshaj** [comment]
Explored the possible options to account for this. Unfortunately, I couldn't find a way to specify a text area through Wooey. Closing this issue.
